  name: Build Resume

  on:
    push:
      branches:
        - main

  jobs:
    build:
      runs-on: ubuntu-latest

      steps:
       - name: Checkout source
         uses: actions/checkout@v3

       - name: Setup Python
         uses: actions/setup-python@v4
         with:
           python-version: '3.13.5'

       - name: Install dependencies and build resume
         run: |
           pip install -r requirements.txt
           python create_resume.py
