name: Build Resume

on:
  push:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.5'

      - name: Install dependencies and build resume
        run: |
          pip install -r requirements.txt
          python create_resume.py

      - name: Commit and push resume.pdf
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "[auto] test: update resume.pdf"
          file_pattern: resume.pdf
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "actions@github.com"
